name: Deploy to Production
on:
  push:
    branches:
      - main
  pull_request:
    types:
      - closed
jobs:
  build-and-deploy:
    if: github.event.pull_request.merged == true || github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23'
          cache: true
          cache-dependency-path: go.sum
      - name: Verify dependencies
        run: go mod verify
      - name: Build project
        run: |
          GOOS=linux GOARCH=amd64 go build -o app_git_trending ./cmd/main.go
      - name: Run tests
        run: go test ./... -v
      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SERVER_SSH_KEY }}
      - name: Add SSH known hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H ${{ secrets.SERVER_HOST }} >> ~/.ssh/known_hosts
      - name: Deploy to server
        run: |
          # Tạo các thư mục cần thiết trên server
          ssh ${{ secrets.SERVER_USERNAME }}@${{ secrets.SERVER_HOST }} '
            sudo mkdir -p /opt/github_trending &&
            mkdir -p ~/temp_deploy
          '
          
          # Copy file binary vào thư mục tạm
          scp app_git_trending ${{ secrets.SERVER_USERNAME }}@${{ secrets.SERVER_HOST }}:~/temp_deploy/
          
          # Di chuyển file và set quyền
          ssh ${{ secrets.SERVER_USERNAME }}@${{ secrets.SERVER_HOST }} '
            sudo mv ~/temp_deploy/app_git_trending /opt/github_trending/ &&
            sudo chown root:root /opt/github_trending/app_git_trending &&
            sudo chmod +x /opt/github_trending/app_git_trending &&
            rm -rf ~/temp_deploy
          '
          
          # Restart service
          ssh ${{ secrets.SERVER_USERNAME }}@${{ secrets.SERVER_HOST }} 'sudo systemctl restart github-trending.service'