name: Deploy to Production

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - closed

jobs:
  build-and-deploy:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23'
          cache: true
          cache-dependency-path: go.sum

      - name: Verify dependencies
        run: go mod verify

      - name: Build project
        run: |
          GOOS=linux GOARCH=amd64 go build -o app_git_trending ./cmd/main.go  # Adjust the path to your main.go

      - name: Run tests
        run: go test ./... -v

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SERVER_SSH_KEY }}

      - name: Add SSH known hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H ${{ secrets.SERVER_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy to server
        run: |
          # Create directory for the app if it doesn't exist
          # ssh ${{ secrets.SERVER_USERNAME }}@${{ secrets.SERVER_HOST }} 'mkdir -p /opt/github_trending'
          
          # Copy the binary and any additional files
          scp app_git_trending ${{ secrets.SERVER_USERNAME }}@${{ secrets.SERVER_HOST }}:/opt/github_trending/
          
          # Optional: Copy config files if needed
          # scp config.yaml ${{ secrets.SERVER_USERNAME }}@${{ secrets.SERVER_HOST }}:/opt/github_trending/
          
          # Restart the service
          ssh ${{ secrets.SERVER_USERNAME }}@${{ secrets.SERVER_HOST }} 'sudo systemctl restart github-trending.service'